### ISSUE TITLE
itemduct

### ISSUE THREAD

**Issue by ziceptor** [CubeEngine/modules-extra#32]
Storage Units with Dropper stopped working.

forge-1.12.2-14.23.1.2555-universal.jar
spongeforge-1.12.2-2555-7.1.0-BETA-2842.jar
LibCube.jar latest
itemduct.jar latest

**Comment by Faithcaio** [comment]
Can't upload on Ore right now due to an error.
So here is the build: 
https://repo.cubeengine.org/org/cubeengine/extra-module/itemduct/1.1.1/itemduct-1.1.1.jar
