### ISSUE TITLE
elevator: shift + (lr)click

### ISSUE THREAD

**Issue by ziceptor** [CubeEngine/modules-extra#34]
Changing the direction is always down.

**Comment by ziceptor** [comment]
create https://i.imgur.com/xFpPp2c.png
rename + ... https://i.imgur.com/XzatICC.png

**Comment by Faithcaio** [comment]
Its shift+left click to change the direction upwards.

**Comment by ziceptor** [comment]
^ title ^
See the topic name. RClick is not working. LClick copies the first line to the third.

**Comment by ziceptor** [comment]
https://www.youtube.com/watch?v=4NA3P99AkXE

**Comment by Faithcaio** [comment]
You dont have a sign above in that video. So it cannot go up.
I'll admit it is confusing that it chooses itself instead. I'll fix that.

**Comment by ziceptor** [comment]
Thanks. What about duplicate text? Or I don't understand something. We need more documentation. Or video.

**Comment by Faithcaio** [comment]
here you go:
https://github.com/CubeEngine/modules-extra/blob/master/elevator/src/main/resources/assets/cubeengine/elevator-usage.md

**Comment by ziceptor** [comment]
Thanks.

**Comment by Faithcaio** [comment]
new version and docs are up on ore 
https://ore.spongepowered.org/CubeEngine/CubeEngine---Elevator/versions/1.0.1
