### ISSUE TITLE
itemduct: Could not pass InteractInventoryEvent

### ISSUE THREAD

**Issue by ziceptor** [CubeEngine/modules-extra#35]
https://gist.github.com/ziceptor/417d6fd14f4e1fa823321ca244c4f034

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar

**Comment by ziceptor** [comment]
https://gist.github.com/ziceptor/0dfe2f3952fa5e43ecae4583b058efef

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2970.jar
itemduct.jar latest from ore

This happened after open the workbench.

**Comment by Faithcaio** [comment]
fixed in latest
