### ISSUE TITLE
Allow removal of endpoint inventory

### ISSUE THREAD

**Issue by BrainStone** [CubeEngine/modules-extra#39]
It would be pretty cool if the endpoint would stay intact when the source/target inventory gets removed.  
This would be very handy when working with shulker boxes!

**Comment by Faithcaio** [comment]
Not possible as the data is stored in the TileEntity. If you break it its gone.
When Sponge allows storing custom data in arbitraty blocks this could become possible.

**Comment by BrainStone** [comment]
Ok. THank you for the explanation!
