### ISSUE TITLE
ItemDuct activator not being given back

### ISSUE THREAD

**Issue by BrainStone** [CubeEngine/modules-extra#41]
In the current version (1.1.3) the ItemDuct Activator isn't given back when used!  
No errors or similar. It works but is not given back.

**Comment by Faithcaio** [comment]
Yes its supposed to be used up. You're not getting instant transportation of entire chests for free.

**Comment by BrainStone** [comment]
Could it be made configurable how many uses the activator has?

**Comment by Faithcaio** [comment]
Uploaded a dev build on ore
requires Sponge `1.12.2-2611-7.1.0-BETA-2984`
