### ISSUE TITLE
Add Super ItemDuct-Activator

### ISSUE THREAD

**Issue by BrainStone** [CubeEngine/modules-extra#42]
It would be really cool to be able to craft something like an unbreakable Super ItemDuct-Activator that is crafted from 8 regular ItemDuct-Activator and a Nether Star. Or at least that it has a much higher durability. (Infinite durability as a config option would be much apprechiated!)

**Comment by Faithcaio** [comment]
Note that while in creative mode the activator already has infinite uses.

**Comment by BrainStone** [comment]
I've noticed that. But thanks for pointing it out. I'm just trying to balance it for my survival server. And balancing in the sense that people actually use it. I've recieved many complaints that it's too expensive for anything large.

But I think two tiers should do it, assuming I can customize the amount of usages.

Also I'd like to thank you for your responsiveness and willingness to implement my requests!

**Comment by Faithcaio** [comment]
done
check latest release on ore

**Comment by BrainStone** [comment]
Two things:

Would it be possible to require ItemActivators instead of noraml hoppers?
And it seems like the super activator always has infinite uses. At least when I configured it to have 256.

**Comment by Faithcaio** [comment]
done
I replaced the snapshot on ore
