### ISSUE TITLE
Elevator issue

### ISSUE THREAD

**Issue by Kirin92** [CubeEngine/modules-extra#50]
Hey~

I have a problem. I want to use your elevator plugin but it kinda don't work for me or I'm just stupid.
I followed your instructions and everything was fine but if I want to change the floor, the arrows don't show up. I tried shift+lclick and shift+rclick but nothing works. I can't change the target.
Here a gif to show you.
https://s3.gifyu.com/images/2019-07-23_11-50-09.gif

**Comment by Faithcaio** [comment]
I had a problem detecting an "empty hand" `Optional.empty()` vs `Optional.of(ItemStack.empty())`.
Fixed in: https://ore.spongepowered.org/CubeEngine/CubeEngine---Elevator/versions/1.0.2
